spring:
  application:
    name: teaming

  datasource:
    url: jdbc:mysql://localhost:3306/ProjectTeaming
    username: root
    password: altMember
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

#jwt:
#  secret: ${JWT_SECRET}